# Generated by Django 5.2.14 on 2026-05-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=50)),
                ('prescription_od', models.CharField(blank=True, default='', max_length=100)),
                ('prescription_os', models.CharField(blank=True, default='', max_length=100)),
                ('lens_type', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('Consultation', 'Consultation'), ('Fitting', 'Fitting'), ('In Production', 'In Production'), ('Ready', 'Ready'), ('Completed', 'Completed')], default='Consultation', max_length=50)),
                ('last_visit', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
