# Generated by Django 5.2.14 on 2026-05-30 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='last_visit',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
