# Generated by Django 5.2.14 on 2026-05-30 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_backfill_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
    ]
