# Generated by Django 5.2.14 on 2026-05-31 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_prescriptionrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(default='Eye Clinic', max_length=200)),
            ],
            options={
                'verbose_name': 'Clinic Setting',
                'verbose_name_plural': 'Clinic Settings',
            },
        ),
    ]
